format = """
[](#9A348E)\
$os\
$memory_usage\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
\n$character"""

[character]
success_symbol = "[->](bold #86BBD8)"
error_symbol = "[->](bold #FCA17D)"

[c]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[docker_context]
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
style = "bg:#33658A"
format = '[ $symbol $state ]($style)'

[nodejs]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[os]
style = "bg:#9A348E"
disabled = false

[os.symbols]
NixOS = "❄"

[rust]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'